### ISSUE TITLE
Dynamic nodes not updating

### ISSUE THREAD

**Issue by sjschukin** [andreister/MvcBreadcrumbs#2]
in MvcBreadcrumbsDemo project I changed UserNodeTitleProvider and  UserSettingsNodeTitleProvider classes as follows:

<pre>
namespace MvcBreadcrumbsDemo.Breadcrumbs
{
    public class UserNodeTitleProvider : AbstractTitleProvider
    {
        protected override string GetTitleInternal(Node node, long id)
        {
            var name = GetUserNameByUserId(id);
            return name;
        }

        private string GetUserNameByUserId(long id)
        {
            return string.Format("[User{0}]", id);
        }
    }
}
</pre>

and

<pre>
namespace MvcBreadcrumbsDemo.Breadcrumbs
{
    public class UserSettingsNodeTitleProvider : AbstractTitleProvider
    {
        protected override string GetTitleInternal(Node node, long id)
        {
            //id here is "settingId" - based on it,
            var name = GetUserNameBySettingId(id);
            node.UpdateParentData(parentData => {
                parentData.Title = name;
                parentData.RouteValues["id"] = id;
            });

            return "Settings";
        }

        private string GetUserNameBySettingId(long id)
        {
            return string.Format("[User{0}]", id);
        }
    }
}
</pre>

After start of the project, you can see that the node with the user name is only updated the first time.

**Comment by sjschukin** [comment]
If parent node been manually updated, then _isUpdatedByChild variable is set to true. Next time "Title" property will not be set in code:

<pre>
if (_titleProvider != null && !_isUpdatedByChild) {
    Data.Title = _titleProvider.GetTitle(this, context);
}
</pre>

**Comment by andreister** [comment]
Good catch - fixed.
