### ISSUE TITLE
value cannot be null in production environment

### ISSUE THREAD

**Issue by toregua** [andreister/MvcBreadcrumbs#4]
Hi andreister and thanks for your nice breadcrumb.

I use it for a while and I did not meet any problems.

Today in my production environment i have a big problem. An error is occured and when I try to debug from my local machine I have no problem.

If I restart IIS it works again on exactly the same page until a moment when this error appear.

I attached a screen from the error. Hope you could help me.

Thanks in advance,

![breadcrumb](https://f.cloud.github.com/assets/4659609/1523011/a1145726-4bb0-11e3-8e47-289885f1e4fd.PNG)

toregua

**Comment by andreister** [comment]
Hmm, given it fails on a `Dictionary` insert, looks like the problem is in

``` C#
foreach (string key in data.QueryString.Keys) {
    routeValues[key] = data.QueryString[key];
}
```

and possibly one your query string keys is `null`. Any ideas? You may want to add some logging to my code - not sure what else could help!

**Comment by toregua** [comment]
Thanks for your help and your quick answer :) In fact I was missing a ";" after my ViewBag.Title = "blabla" (;) in my asp.net mvc razor view and it was only that... thanks again
